### ISSUE TITLE
Can you write a proper document? 

### ISSUE THREAD

**Issue by zinwalin** [Soontao/go-simple-api-gateway#3]
It is really hard to set up and test. Please update document for setup, casbin policy example, mysql sql.

**Comment by Soontao** [comment]
Hello @zinwalin,

Thank you for your interest in this project.

In fact, this project is a simple gateway prototype, with predefined casbin policy and single target http proxy, and it works two years ago. 

This project is **deprecated** now and lost many gateway features (rate-limit/monitor/log), if you are finding an API gateway in production, I suggest you choose the [kong](https://github.com/Kong/kong) or amazon API gateway/azure API management. 

Thanks.

**Comment by zinwalin** [comment]
> Hello @zinwalin,
> 
> Thank you for your interest in this project.
> 
> In fact, this project is a simple gateway prototype, with predefined casbin policy and single target http proxy, and it works two years ago.
> 
> This project is **deprecated** now and lost many gateway features (rate-limit/monitor/log), if you are finding an API gateway in production, I suggest you choose the [kong](https://github.com/Kong/kong) or amazon API gateway/azure API management.
> 
> Thanks.

thanks a lot.
